apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: nginx
  selfLink: /api/v1/namespaces/nginx-ns/pods/nginx
spec:
  containers:
  - image: nginx:1.15.8
    imagePullPolicy: IfNotPresent
    name: nginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-8dnsw
      readOnly: true
    livenessProbe:
      httpGet:
        path: /
        port: 80
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: nabheetsap2c.mylabserver.com
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-8dnsw
    secret:
      defaultMode: 420
      secretName: default-token-8dnsw
status:
  phase: Pending
  qosClass: BestEffort
