apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe
spec:
  containers:
  - name: liveness-container
    image: busybox
    command: ['sh','-c','echo k8s && sleep 3600']
    livenessProbe:
      exec:
        command:
        -  echo
        -  testing
      initialDelaySeconds: 5
      periodSeconds: 5
