apiVersion: v1
kind: Pod
metadata:
  name: readiveness-probe
spec:
  containers:
  - name: readiveness-container
    image: nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5

