apiVersion: v1
kind: Pod
metadata:
  name: my-secreat-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo  $MY_PASSWORD  && sleep 3600']
    env:
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef: 
          name: my-secret
          key: myKey  
