apiVersion: v1
kind: Pod
metadata:
  name: my-seraccount-pod
spec:
  serviceAccountName: my-serviceaccount
  containers:
  - name: my-seracc-container
    image: busybox
    command: ["sh","-c","echo k8s && sleep 3600"]
