apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-05-07T14:53:27Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "88340"
  selfLink: /api/v1/namespaces/default/pods/nginx
  uid: 822dde49-9072-11ea-94c7-0a0a8defb6e6
spec:
  containers:
  - image: nginx:1.7.1
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ld2x7
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: nabheetsap2c.mylabserver.com
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-ld2x7
    secret:
      defaultMode: 420
      secretName: default-token-ld2x7
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-05-07T14:53:26Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-05-07T14:53:31Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-05-07T14:53:31Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-05-07T14:53:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://3fab0d26f0b26fa609e22121418d15241bf9595733ba0d5ef2648867509d5290
    image: nginx:1.7.1
    imageID: docker-pullable://nginx@sha256:7fbe0579e123f3d2b29c9159e9a80547fb72621bb419e52d98c679ddbf1055a1
    lastState:
      terminated:
        containerID: docker://e31e0062f161d0aec4ea5d5ed55ab46e8f16e7d041d124e23c6410ab6eeb2c66
        exitCode: 0
        finishedAt: "2020-05-07T14:54:21Z"
        reason: Completed
        startedAt: "2020-05-07T14:53:30Z"
    name: nginx
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2020-05-07T14:54:37Z"
  hostIP: 172.31.31.104
  phase: Running
  podIP: 10.244.1.3
  qosClass: BestEffort
  startTime: "2020-05-07T14:53:26Z"
