apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busyboxi
            args:
            - /bin/sh
            - -c
            - date; echo hello from k8s
          restartPolicy: OnFailure
