apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-rolling
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-dep2
  template:
    metadata:
      labels:
        app: nginx-dep2
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
        ports:
        - containerPort: 80
